ATTSystems.ProjectCore/Controllers/SettingController.cs
/* Copyright © ATT Systems Pte Ltd. All Rights Reserved
 * Project      : ATTSystems.ProjectCore
 * Author       : Mark Tan
 * Created Date : 2019-06-07
 * Updated Date : 
 */

namespace ATTSystems.ProjectCore.Controllers
{
    using ATTSystems.Core.Logger;
    using ATTSystems.Core.Model.HttpModel;
    using ATTSystems.Core.Model.ViewModel;
    using ATTSystems.ProjectCore.Helper;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    [LocalAuthorize]
    public class SettingController : Controller
    {
        [HttpGet]
        public async Task<ActionResult> ListDepartment()
        {
            APIRequest req = new APIRequest
            {
                RequestType = "ListDepartment",
                RequestString = User.Identity.Name,
                UserName = User.Identity.Name,
                Message = string.Empty
            };

            List<DepartmentViewModel> result = null;
            //APIResponse
            var resp = await WebAPIHelper.APIRequestAsync("/Setting/GetDepartmentList/", req);
            if (resp != null && resp.DepartmentList != null)
            {
                result = resp.DepartmentList;
            }
            else
            {
                result = new List<DepartmentViewModel>();
            }

            return View(result);
        }

        [HttpGet]
        public ActionResult CreateDepartmentModal()
        {
            return PartialView("_AddDepartment", new DepartmentViewModel());
        }

        [HttpGet]
        public async Task<ActionResult> EditDepartmentModal(int id)
        {
            APIRequest req = new APIRequest
            {
                UserName = User.Identity.Name,
                Message = "Get department by id",
                RequestString = id.ToString(),
                RequestType = "Get single department",
            };

            var resp = await WebAPIHelper.APIRequestAsync("/Setting/GetDepartment/", req);

            if (resp != null && resp.Succeeded && resp.DepartmentList != null && resp.DepartmentList.Count > 0)
            {
                DepartmentViewModel model = resp.DepartmentList.FirstOrDefault();
                return PartialView("_EditDepartment", model);
            }
            else
            {
                string errmsg = (resp != null && !string.IsNullOrEmpty(resp.Message)) ? resp.Message : "Invalid input";

                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest, errmsg);
            }


        }

        [HttpPost]
        public async Task<ActionResult> DeleteDepartment(IdCollection idColl)
        {
            dynamic showMessageString = string.Empty;

            try
            {
                APIRequest req = new APIRequest
                {
                    UserName = User.Identity.Name,
                    Message = "Delete Department",
                    RequestString = idColl.IdList,
                    RequestType = "Delete",
                };

                var resp = await WebAPIHelper.APIRequestAsync("/Setting/DeleteDepartment/", req);
                if (resp != null && resp.Succeeded)
                {
                    showMessageString = new
                    {
                        Code = 200,
                        Message = string.Format("Department is sucessfully deleted"),
                        ModalType = "Delete",
                    };
                }
                else
                {
                    showMessageString = new
                    {
                        Code = 300,
                        Message = "Failed! Department setting is not deleted.",
                        ModalType = "Delete",
                    };
                }

                return Json(showMessageString, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                LoggerHelper.Instance.TraceLog(string.Format("Level: Warning, Type: WebApp, Controller: Setting, Action: DeleteDepartment, Message: {0} ", ex.Message));

                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Error in processing new settings.");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditDepartment(DepartmentViewModel model)
        {
            dynamic showMessageString = string.Empty;
            try
            {
                if (ModelState.IsValid && model != null)
                {
                    APIRequest request = new APIRequest
                    {
                        Model = model,
                        UserName = User.Identity.Name,
                    };

                    APIResponse resp = await WebAPIHelper.APIRequestAsync("/Setting/UpdateDepartment/", request);
                    if (resp == null || !resp.Succeeded)
                    {
                        string err = resp != null ? resp.Message : string.Empty;
                        showMessageString = new
                        {
                            Code = 300,
                            Message = "Failed. Department is not Updated.\n" + err,
                            ModalType = "Update",
                        };
                    }
                    else
                    {
                        showMessageString = new
                        {
                            Code = 200,
                            Message = string.Format("Department is sucessfully updated [id: {0}].", resp.Code),
                            ModalType = "Update",
                            Department_Name = model.Department_Name,
                            Description = model.Description,
                            Department_ID = model.Department_ID,
                        };
                    }
                }
                else
                {
                    string errmsg = string.Empty;
                    foreach (string key in ViewData.ModelState.Keys)
                    {
                        string modelStateError = string.Empty;
                        var modelState = ViewData.ModelState[key];
                        if (modelState.Errors != null && modelState.Errors.Count > 0)
                        {
                            errmsg = string.Format("{0}|{1}:{2}", errmsg, key, modelState.Errors.FirstOrDefault().ErrorMessage);
                        }
                    }

                    showMessageString = new
                    {
                        Code = 201, // invalid format
                        Message = !string.IsNullOrEmpty(errmsg) ? errmsg.Substring(1) : errmsg,
                        ModalType = "Update",
                    };
                }
            }
            catch (Exception ex)
            {
                LoggerHelper.Instance.TraceLog(string.Format("Level: Warning, Type: WebApp, Controller: Setting, Action: EditDepartment, Message: {0} ", ex.Message));
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "Error in processing new Department.");
            }

            return Json(showMessageString, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateDepartment(DepartmentViewModel model)
        {
            dynamic showMessageString = string.Empty;

            try
            {
                if (ModelState.IsValid && model != null)
                {
                    APIRequest request = new APIRequest
                    {
                        Model = model,
                        UserName = User.Identity.Name,
                    };

                    APIResponse resp = await WebAPIHelper.APIRequestAsync("/Setting/AddDepartment/", request);
                    if (resp == null || !resp.Succeeded)
                    {
                        string err = resp != null ? resp.Message : string.Empty;
                        showMessageString = new
                        {
                            Code = 300,
                            Message = "Failed. Department is not created.\n" + err,
                            ModalType = "Add",
                        };
                    }
                    else
                    {
                        showMessageString = new
                        {
                            Code = 200,
                            Message = string.Format("Department is sucessfully created [id: {0}].", resp.Code),
                            ModalType = "Add",
                        };
                    }
                }
                else
                {
                    string errmsg = string.Empty;
                    foreach (string key in ViewData.ModelState.Keys)
                    {
                        string modelStateError = string.Empty;
                        var modelState = ViewData.ModelState[key];
                        if (modelState.Errors != null && modelState.Errors.Count > 0)
                        {
                            errmsg = string.Format("{0}|{1}:{2}", errmsg, key, modelState.Errors.FirstOrDefault().ErrorMessage);
                        }
                    }

                    showMessageString = new
                    {
                        Code = 201, // invalid format
                        Message = !string.IsNullOrEmpty(errmsg) ? errmsg.Substring(1) : errmsg,
                        ModalType = "Add",
                    };
                }
            }
            catch (Exception ex)
            {
                LoggerHelper.Instance.TraceLog(string.Format("Level: Warning, Type: WebApp, Controller: Setting, Action: CreateDepartment, Message: {0} ", ex.Message));

ATTSystems.ProjectCore/Views/Setting/ListDepartment.cshtml
@model IEnumerable<ATTSystems.Core.Model.ViewModel.DepartmentViewModel>
@{
    ViewBag.Title = "Department Listing";
    Layout = null;
}

<div class="row">
    <div class="col-lg-6">
        <h4 style="padding-left: 10px; padding-top: 10px;">Department Listing</h4>
    </div>
    <div class="col-lg-6">
        <div class="align-right" style="padding-right: 10px; padding-top: 10px;">
            <button type="button" data-toggle="modal" data-target="#myModal" id="btnAdd"
                    class="btn bg-blue btn-circle waves-effect waves-circle waves-float btnAdd" value="Add" title="Add">
                <i class="material-icons">&#xE145;</i>
            </button>
        </div>
    </div>
</div>
        <div class="body">
            <table class="table table-bordered table-striped table-hover js-basic-example dataTable customTbl">
                <thead>
                    <tr>
                        <th>
                            Department Name
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="row@(item.Department_ID)">
                            <td id="col_Department_Name">
                                @Html.DisplayFor(modelItem => item.Department_Name)
                            </td>
                            <td id="col_Description">
                                <span title="@Html.DisplayFor(modelItem => item.Description)">@Html.DisplayFor(modelItem => item.Description)</span>
                            </td>
                            <td align="center">
                                <a href="#" data-id="@item.Department_ID" class="lnkEdit" title="Edit" data-para="@item.Department_ID"><i class="material-icons">mode_edit</i></a>
                                <a href="#" data-id="@item.Department_ID" class="lnkDelete" title="Delete" data-para="@item.Department_ID"><i class="material-icons">delete</i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- Modal Area -->
        <div id="modalDiv">

        </div>
        <script src='@Url.Content("~/Scripts/jquery-datatable.js")'></script>
        <script src='@Url.Content("~/Scripts/jquery.dataTables.js")'></script>
        <script src='@Url.Content("~/Scripts/dataTables.bootstrap.js")'></script>

        <script type="text/javascript">
    $(function () {
        /* Add Method Here */
        $('#btnAdd').click(function () {
            $('.btnAdd').attr('disabled', true);
            setTimeout(function () {
                $('.btnAdd').attr('disabled', false);
            }, 4000);
            var relativeURI = "@Url.Action("CreateDepartmentModal", "Setting")";
            RenderPartialView(relativeURI, "#addDepartmentModal");
        });

        /* Delete Method Here */
        $('.customTbl').on('click', '.lnkDelete', function () {
            var _deptid = $(this).attr('data-para');
            deleteDialog("Setting", "DeleteDepartment", [_deptid]);
        });

        /* Edit Method Here */
        $('.customTbl').on('click', '.lnkEdit', function () {
            /* Disable link for 4 seconds */

            $('.lnkEdit').addClass('tmpEdit');
            $('.tmpEdit').removeClass('lnkEdit');
            setTimeout(function () {
                $('.tmpEdit').addClass('lnkEdit');
                $('.lnkEdit').removeClass('tmpEdit');
            }, 3000);
            /* End of disable link for 4 seconds */
            var _msgId = $(this).attr('data-para');

            if (_msgId > 0) {
                var relativeURI = "@Url.Action("EditDepartmentModal", "Setting", new { id = "_para1" })".replace("_para1", _msgId);
                RenderPartialView(relativeURI, "#editDepartmentModal");
            }
        });
    });

    //script with partial render
    function RenderPartialView(relativeURI, modalType) {
        $.ajax({
            url: relativeURI,
            type: "Get",
            cache: false,
            success: function (data) {
                //custom showing popup
                $("#modalDiv").html("");
                $("#modalDiv").html(data);
                $(modalType).modal('show');
            },
            error: function (data) {
                swal("Warning", data.statusText, "error");
            }

        });
    }

    var prevErr = [];
    function SuccessCreate(e) {
        var msg = e.Message;
        var isDelete = false;
        var isUpdate = false;

        if (e.Code == 200) { // ok
            if (e.ModalType == "Add") {
                $('#addDepartmentModal').modal('hide');
            }
            else if (e.ModalType == "Delete") {
                isDelete = true;
            }
            else {

                $('#editDepartmentModal').modal('hide');

                var rowid = e.Department_ID;
                $('#row' + rowid).find('#col_Department_Name').text(e.Department_Name);
                $('#row' + rowid).find('#col_Description').text(e.Description);
                isUpdate = true;
            }

            showDialog(msg, e.ModalType + " Department", "success", "Setting", "ListDepartment", 0, isUpdate, isDelete);
        }
        else { // ==> validation error

            if (e.Code == 201 && e.ModalType != "Delete") {
                // clear previous error message
                if (prevErr.length > 0) {
                    for (i = 0; i < prevErr.length; i++) {
                        $(prevErr[0]).html("");
                    }
                }

                // process error message
                prevErr = [];
                var errTok = e.Message.split("|");

                for (i = 0; i < errTok.length; i++) {
                    var tok = errTok[i].split(":");

                    prevErr.push('#' + tok[0])
                    $('#' + tok[0]).html(tok[1]);
                }
            }

            showDialog(msg, e.ModalType + " Department", "error", "Setting", "ListDepartment", 0, false, false);
        }
    }

    function FailCreate(e) {
        showDialog(e.statusText, "Department", "error", "", "", 0, false, false);
    }

        </script>

ATTSystems.ProjectCore/Views/Setting/ListRole.cshtml
@model IEnumerable<ATTSystems.Core.Model.ViewModel.RoleViewModel>
@{
    ViewBag.Title = "ListRole";
    Layout = null;
}

<div class="row">
    <div class="col-lg-6">
        <h4 style="padding-left: 10px; padding-top: 10px;">Role Listing</h4>
    </div>
    <div class="col-lg-6">
        <div class="align-right" style="padding-right: 10px; padding-top: 10px;">
            <button type="button" data-toggle="modal" data-target="#myModal" id="btnAdd"
                    class="btn bg-blue btn-circle waves-effect waves-circle waves-float btnAdd" value="Add" title="Add">
                <i class="material-icons">&#xE145;</i>
            </button>
        </div>
    </div>
</div>
        <div class="body">
            <table class="table table-bordered table-striped table-hover js-basic-example dataTable customTbl">
                <thead>
                    <tr>
                        <th>
                            Role
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            Permission
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="row@(item.Id)">

                            <td id="col_Role_Name">
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td id="col_Description">
                                <span title="@Html.DisplayFor(modelItem => item.Description)">@Html.DisplayFor(modelItem => item.Description)</span>
                            </td>
                            <td id="col_Permission">
                                <span title="@Html.DisplayFor(modelItem => item.AllowPermission)">@Html.DisplayFor(modelItem => item.AllowPermission)</span>
                            </td>
                            <td align="center">
                                <a href="#" data-id="@item.Id" class="lnkEdit" title="Edit" data-para="@item.Id"><i class="material-icons">mode_edit</i></a>
                                <a href="#" data-id="@item.Id" class="lnkDelete" title="Delete" data-para="@item.Id"><i class="material-icons">delete</i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- Modal Area -->
        <div id="modalDiv">
        </div>

        <script src='@Url.Content("~/Scripts/jquery-datatable.js")'></script>
        <script src='@Url.Content("~/Scripts/jquery.dataTables.js")'></script>
        <script src='@Url.Content("~/Scripts/dataTables.bootstrap.js")'></script>

        <script type="text/javascript">
    $(function () {
        /* Add Method Here */
        $('#btnAdd').click(function () {
            $('.btnAdd').attr('disabled', true);
            setTimeout(function () {
                $('.btnAdd').attr('disabled', false);
            }, 4000);
            var relativeURI = "@Url.Action("CreateRoleModal", "Setting")";
            RenderPartialView(relativeURI, "#addRoleModal");
        });

        /* Delete Method Here */
        $('.customTbl').on('click', '.lnkDelete', function () {
            var _rowid = $(this).attr('data-para');
            deleteDialog("Setting", "DeleteRole", [_rowid]);
        });

                /* Edit Method Here */
        $('.customTbl').on('click', '.lnkEdit', function () {
            /* Disable link for 4 seconds */

            $('.lnkEdit').addClass('tmpEdit');
            $('.tmpEdit').removeClass('lnkEdit');
            setTimeout(function () {
                $('.tmpEdit').addClass('lnkEdit');
                $('.lnkEdit').removeClass('tmpEdit');
            }, 3000);
            /* End of disable link for 4 seconds */
            var _msgId = $(this).attr('data-para');

            if (_msgId != "") {
                var relativeURI = "@Url.Action("EditRoleModal", "Setting", new { id = "_para1" })".replace("_para1", _msgId);
                RenderPartialView(relativeURI, "#editRoleModal");
            }
        });
    });

    //script with partial render
    function RenderPartialView(relativeURI, modalType) {
        $.ajax({
            url: relativeURI,
            type: "Get",
            cache: false,
            success: function (data) {
                //custom showing popup
                $("#modalDiv").html("");
                $("#modalDiv").html(data);
                $(modalType).modal('show');
            },
            error: function (data) {
                swal("Warning", data.statusText, "error");
            }

        });
    }

    var prevErr = [];
    function SuccessCreate(e) {
        var msg = e.Message;
        var isDelete = false;
        var isUpdate = false;

        if (e.Code == 200) { // ok
            if (e.ModalType == "Add") {
                $('#addRoleModal').modal('hide');
            }
            else if (e.ModalType == "Delete") {
                isDelete = true;
            }
            else {
                $('#editRoleModal').modal('hide');
            }

            showDialog(msg, e.ModalType + " Role", "success", "Setting", "ListRole", 0, isUpdate, isDelete);
        }
        else { // ==> validation error

            if (e.Code == 201 && e.ModalType != "Delete") {
                // clear previous error message
                if (prevErr.length > 0) {
                    for (i = 0; i < prevErr.length; i++) {
                        $(prevErr[0]).html("");
                    }
                }

                // process error message
                prevErr = [];
                var errTok = e.Message.split("|");

                for (i = 0; i < errTok.length; i++) {
                    var tok = errTok[i].split(":");

                    prevErr.push('#' + tok[0])
                    $('#' + tok[0]).html(tok[1]);
                }
            }

            showDialog(msg, e.ModalType + " Role", "error", "Setting", "ListRole", 0, false, false);
        }
    }

    function FailCreate(e) {
        showDialog(e.statusText, "Role", "error", "", "", 0, false, false);
    }
        </script>

ATTSystems.ProjectCore/Views/Setting/ListUser.cshtml
@model IEnumerable<ATTSystems.Core.Model.ViewModel.UserViewModel>
@{
    ViewBag.Title = "ListUser";
    Layout = null;
}

<div class="row">
    <div class="col-lg-6">
        <h4 style="padding-left: 10px; padding-top: 10px;">User Listing</h4>
    </div>
    <div class="col-lg-6">
        <div class="align-right" style="padding-right: 10px; padding-top: 10px;">
            <button type="button" data-toggle="modal" data-target="#myModal" id="btnAdd"
                    class="btn bg-blue btn-circle waves-effect waves-circle waves-float btnAdd" value="Add" title="Add">
                <i class="material-icons">&#xE145;</i>
            </button>
        </div>
    </div>
</div>

        <div class="body">
            <table class="table table-bordered table-striped table-hover js-basic-example dataTable customTbl">
                <thead>
                    <tr>
                        <th>
                            User
                        </th>
                        <th>
                            Department
                        </th>
                        <th>
                            Role
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="row@(item.Id)">
                            <td id="col_Username">
                                @Html.DisplayFor(modelItem => item.UserName)
                            </td>
                            <td id="col_UserDepartment">
                                <span title="@Html.DisplayFor(modelItem => item.DepartmentItems)">@Html.DisplayFor(modelItem => item.DepartmentItems)</span>
                            </td>
                            <td id="col_UserRole">
                                <span title="@Html.DisplayFor(modelItem => item.RoleItems)">@Html.DisplayFor(modelItem => item.RoleItems)</span>
                            </td>
                            <td align="center">
                                @if (item.UserName.ToLower() == "administrator")
                                {
                                    <i class="material-icons" style="color: lightgray;">mode_edit</i>
                                    <i class="material-icons" style="color: lightgray;">delete</i>
                                }
                                else
                                {
                                    <a href="#" data-id="@item.Id" class="lnkEdit" title="Edit" data-para="@item.Id"><i class="material-icons">mode_edit</i></a>
                                    <a href="#" data-id="@item.Id" class="lnkDelete" title="Delete" data-para="@item.Id"><i class="material-icons">delete</i></a>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <!-- Modal Area -->
        <div id="modalDiv">
        </div>

        <script src='@Url.Content("~/Scripts/jquery-datatable.js")'></script>
        <script src='@Url.Content("~/Scripts/jquery.dataTables.js")'></script>
        <script src='@Url.Content("~/Scripts/dataTables.bootstrap.js")'></script>

        <script type="text/javascript">
    $(function () {

        /* Add Method Here */
        $('#btnAdd').click(function () {
            $('.btnAdd').attr('disabled', true);
            setTimeout(function () {
                $('.btnAdd').attr('disabled', false);
            }, 4000);
            var relativeURI = "@Url.Action("CreateUserModal", "Setting")";
            RenderPartialView(relativeURI, "#addUserModal");
        });

        /* Delete Method Here */
        $('.customTbl').on('click', '.lnkDelete', function () {
            var _rowid = $(this).attr('data-para');
            deleteDialog("Setting", "DeleteUser", [_rowid]);
        });

        /* Edit Method Here */
        $('.customTbl').on('click', '.lnkEdit', function () {
            /* Disable link for 4 seconds */

            $('.lnkEdit').addClass('tmpEdit');
            $('.tmpEdit').removeClass('lnkEdit');
            setTimeout(function () {
                $('.tmpEdit').addClass('lnkEdit');
                $('.lnkEdit').removeClass('tmpEdit');
            }, 3000);
            /* End of disable link for 4 seconds */
            var _msgId = $(this).attr('data-para');

            if (_msgId != "") {
                var relativeURI = "@Url.Action("EditUserModal", "Setting", new { id = "_para1" })".replace("_para1", _msgId);
                RenderPartialView(relativeURI, "#editUserModal");
            }
        });
    });

    //script with partial render
    function RenderPartialView(relativeURI, modalType) {
        $.ajax({
            url: relativeURI,
            type: "Get",
            cache: false,
            success: function (data) {
                //custom showing popup
                $("#modalDiv").html("");
                $("#modalDiv").html(data);
                $(modalType).modal('show');
            },
            error: function (data) {
                alert("==1== " + data.statusText)
                swal("Warning", data.statusText, "error");
            }

        });
    }

    var prevErr = [];
    function SuccessCreate(e) {
        var msg = e.Message;
        var isDelete = false;
        var isUpdate = false;

        if (e.Code == 200) { // ok
            if (e.ModalType == "Add") {
                $('#addUserModal').modal('hide');
            }
            else if (e.ModalType == "Delete") {
                isDelete = true;
            }
            else {
                $('#editUserModal').modal('hide');
            }

            showDialog(msg, e.ModalType + " User", "success", "Setting", "ListUser", 0, isUpdate, isDelete);
        }
        else { // ==> validation error

            if (e.Code == 201 && e.ModalType != "Delete") {
                // clear previous error message
                if (prevErr.length > 0) {
                    for (i = 0; i < prevErr.length; i++) {
                        $(prevErr[0]).html("");
                    }
                }

                // process error message
                prevErr = [];
                var errTok = e.Message.split("|");

                for (i = 0; i < errTok.length; i++) {
                    var tok = errTok[i].split(":");

                    prevErr.push('#' + tok[0])
                    $('#' + tok[0]).html(tok[1]);
                }
            }

            showDialog(msg, e.ModalType + " User", "error", "Setting", "ListUser", 0, false, false);
        }
    }

    function FailCreate(e) {
        showDialog(e.statusText, "User", "error", "", "", 0, false, false);
    }
        </script>